### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by peku33** [bryanforbes/asyncpg-stubs#103]
While mypy checks completes successfully, the actual python interpreter (Python 3.10.1) rejects parameter of type `asyncpg.Pool[asyncpg.Record]` with error `TypeError: 'type' object is not subscriptable`.

Is:
`pool: asyncpg.Pool[asyncpg.Record]`
a correct way to declare a parameter?

**Comment by bryanforbes** [comment]
Since the generic types are only in stubs, you will need to either us `from __future__ import annotations` at the top of the file or you'll need to surround it in quotes. For more information, you'll want to check out the section on [using classes that are generic in stubs but not at runtime](https://mypy.readthedocs.io/en/stable/runtime_troubles.html?highlight=subscriptable#using-classes-that-are-generic-in-stubs-but-not-at-runtime) in the mypy docs (but it applies to all type checkers).
