### ISSUE TITLE
asyncpg.Record is not a mapping

### ISSUE THREAD

**Issue by poofeg** [bryanforbes/asyncpg-stubs#122]
Why doesn't `asyncpg.Record` inherit `collections.abc.Mapping[str, Any]`? This is a valid code:
```python
record: asyncpg.Record
...
some_func(**record)
```
But mypy says: `error: Argument after ** must be a mapping, not "Record"`.

**Comment by bryanforbes** [comment]
I opened a [discusson](https://github.com/python/typing/discussions/1375) over at the Python Type School to find out how to solve this issue and it turns out that this is a bug in both `mypy` and `pyright`. The bug in `pyright` [has been fixed](https://github.com/microsoft/pyright/issues/4826) in version 1.1.301 and I have opened [an issue](https://github.com/python/mypy/issues/14986) with `mypy` to fix it there. Once that has been addressed in `mypy`, the code you have shared here will work.

**Comment by bryanforbes** [comment]
`mypy` version 1.3 has been released with [the fix](https://github.com/python/mypy/pull/14990) for this issue. Consequently, this is no longer a problem with `pyright` or `mypy`.
